# Generated by Django 5.2.4 on 2025-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=100)),
                ('ship_mode', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('month', models.IntegerField()),
                ('dayofweek', models.IntegerField()),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
