# Generated by Django 5.2.4 on 2025-07-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='sales',
            new_name='predicted_sales',
        ),
    ]
