# Generated by Django 5.2.4 on 2025-07-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_rename_sales_store_predicted_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='predicted_sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
