# Generated by Django 5.2.4 on 2025-07-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_store_discount_alter_store_predicted_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='predicted_sales',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
